
name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Build Docker Image
        run: docker build -t ghcr.io/singhisking100/hello-world .

      - name: Log in to GitHub Container Registry
Run docker pull ghcr.io/singhisking100/hello-world:latest
  docker pull ghcr.io/singhisking100/hello-world:latest
  shell: /usr/bin/bash -e {0}
Error response from daemon: denied
Error: Process completed with exit code 1.
              

      - name: Push Docker Image to GHCR
        run: docker push ghcr.io/singhisking100/hello-world




